# Generated by Django 3.2.12 on 2024-01-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Dream')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=500)),
                ('feeling', models.CharField(choices=[('G', 'Good'), ('O', 'Okay'), ('N', 'Not Good'), ('B', 'Bad')], default='G', max_length=1)),
                ('dream_type', models.CharField(choices=[('N', 'Nightmare'), ('A', 'Amazing'), ('W', 'Weird')], default='Nightmare', max_length=1)),
            ],
        ),
    ]
