# Generated by Django 3.2.12 on 2024-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dreams_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Dream')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=500)),
                ('feeling', models.CharField(choices=[('G', 'Good'), ('O', 'Okay'), ('N', 'Not Good'), ('B', 'Bad')], default='G', max_length=1)),
                ('dream_type', models.CharField(choices=[('N', 'Nightmare'), ('A', 'Amazing'), ('W', 'Weird')], default='Nightmare', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('color3', models.CharField(max_length=7)),
                ('color4', models.CharField(max_length=7)),
                ('color5', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Dreams',
        ),
    ]
