# Generated by Django 4.2.9 on 2024-01-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_dream_options_dream_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dream',
            options={},
        ),
        migrations.AlterField(
            model_name='dream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dream_images/'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dream')),
            ],
        ),
    ]
