# Generated by Django 4.2.9 on 2024-01-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_dream_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Palette',
        ),
        migrations.AlterField(
            model_name='dream',
            name='dream_type',
            field=models.CharField(choices=[('N', 'nightmare'), ('A', 'dream'), ('W', 'weird dream')], default='nightmare', max_length=1),
        ),
        migrations.AlterField(
            model_name='dream',
            name='feeling',
            field=models.CharField(choices=[('G', 'great'), ('O', 'okay'), ('N', 'not good'), ('B', 'terrible')], default='G', max_length=1),
        ),
    ]
